// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-OAd0QyAxVEMO3beeY5p-7UW-GsOby8Y',
    appId: '1:221707905165:web:48a1ca0b3334f8b36d9ac4',
    messagingSenderId: '221707905165',
    projectId: 'testproject-cbad9',
    authDomain: 'testproject-cbad9.firebaseapp.com',
    storageBucket: 'testproject-cbad9.appspot.com',
    measurementId: 'G-LNGB7NV7FF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1IivjUB60stpxqPHCtvCn-wStaxlAWlU',
    appId: '1:221707905165:android:292796a885f1a94a6d9ac4',
    messagingSenderId: '221707905165',
    projectId: 'testproject-cbad9',
    storageBucket: 'testproject-cbad9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVdoLb7C9Omv22AtPcmxAzAoC0jIn0fLQ',
    appId: '1:221707905165:ios:c6ee60d27b9c556a6d9ac4',
    messagingSenderId: '221707905165',
    projectId: 'testproject-cbad9',
    storageBucket: 'testproject-cbad9.appspot.com',
    iosClientId: '221707905165-7b4tmqkgamtt457jvjvq7jd92b452fds.apps.googleusercontent.com',
    iosBundleId: 'com.example.faceDetectionProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVdoLb7C9Omv22AtPcmxAzAoC0jIn0fLQ',
    appId: '1:221707905165:ios:c6ee60d27b9c556a6d9ac4',
    messagingSenderId: '221707905165',
    projectId: 'testproject-cbad9',
    storageBucket: 'testproject-cbad9.appspot.com',
    iosClientId: '221707905165-7b4tmqkgamtt457jvjvq7jd92b452fds.apps.googleusercontent.com',
    iosBundleId: 'com.example.faceDetectionProject',
  );
}
